document.addEventListener("DOMContentLoaded", function () {
  const form = document.getElementById("chat-form");
  const input = document.getElementById("user-input");
  const chat = document.getElementById("chat-box");

  const odpovede = {
    "pes": "Pes domáci alebo pes je taxón z rodu Canis. Je to domestikovaná podoba vlka dravého. Presné zaradenie tohto taxónu v rámci rodu Canis je sporné.",
    "futbal": "Futbal, zastarano kopaná, je kolektívna loptová hra, ktorá je považovaná za najpopulárnejší šport na svete. Podľa prieskumu FIFA hrá futbal pravidelne najmenej 300 miliónov ľudí vo viac ako 220 krajinách sveta. Dôvodom jeho popularity sú jednoduché pravidlá a minimálna náročnosť na vybavenie.",
    "erikai": "ErikAI je offline umelá inteligencia vytvorená tebou.",
    "slovensko": "Slovensko, dlhý tvar Slovenská republika, je vnútrozemský štát v strednej Európe.[pozn. 2] Je členským štátom Európskej únie a NATO. Má rozlohu 49 036 km² a žije tu okolo 5 447 270 obyvateľov.[13] Na severozápade hraničí s Českom, na juhozápade s Rakúskom, na severe s Poľskom, na východe s Ukrajinou a na juhu s Maďarskom.Krajina je prevažne hornatá, pretože väčšinu povrchu zaberajú vysočiny. Zo severu sem z mohutného oblúka zasahujú Karpaty, na juhu sa rozprestiera Panónska panva. Hlavným a najväčším mestom je Bratislava, úradným jazykom je slovenčina.",
    "bratislava": "Bratislava (Prehrať slovenská výslovnosť, nem. Pressburg, maď. Pozsony, gr. Istropolis – Mesto na Dunaji; do roku 1919 Prešporok/Prešporek; iné názvy pozri nižšie) je hlavné a rozlohou aj počtom obyvateľov najväčšie mesto Slovenska. Podľa posledného sčítania obyvateľov v Bratislave k 31. decembru 2024 žilo 479 389 obyvateľov.",
    "košice": "Košice (iné názvy pozri kapitolu Názov) sú metropolou východného Slovenska a s takmer 230 000 obyvateľmi[5] druhým najľudnatejším mestom na Slovensku. Mesto je súčasťou Košickej aglomerácie s 367 000 obyvateľmi a Košicko-prešovskej aglomerácie, ktorá s 555 800 obyvateľmi patrí medzi najväčšie urbanizované oblasti na Slovensku.",
  "žilina": "Počtom obyvateľov (spolu 80 020, 38 623 mužov, 41 397 žien poďľa údajov 31.10.2024) je Žilina štvrtým najväčším mestom na Slovensku.[4] Je administratívnym, hospodárskym, dopravným a kultúrnym centrom severozápadného Slovenska, niekedy sa jej hovorí „perla na Váhu“.",
  "veľké rovné": "Veľké Rovné je obec na Slovensku v okrese Bytča, ktorá sa nachádza na severozápadnej časti Slovenska. V obci je veľa miestnych častí/osád medzi najväčšie patria: Horevsie, Rimanovice, Žarnov, Ivor.",
    "nitra": "Nitra (maď. Nyitra, nem. Neutra) je mesto ležiace v Nitrianskom kraji vzdialené približne 90 km východne od hlavného mesta Bratislavy. Preteká ňou rovnomenná rieka Nitra. Panorámu Nitry tvorí sedem pahorkov: zo severnej strany sa týči vrch Zobor, Hradná skala, Vŕšok, Kalvária, Borina, Ľupka spolu s Martinským vrchom. Prvé potvrdené historické zmienky sú z roku 828. Po meste je pomenovaná planétka (9543) Nitra. Počtom obyvateľov 75 208 je piatym najväčším mestom na Slovensku.[4]",
      "prešov": "Prešov (nem. Eperies alebo Preschau, maď. Eperjes, lat. Fragopolis alebo Eperiessinum) je krajské mesto ležiace v Prešovskom kraji. Prešov je tretím najľudnatejším mestom na Slovensku s približne 82 300 obyvateľmi. Má štyri katastrálne časti: Prešov, Šalgovík, Solivar a Nižná Šebastová. Patrí do košicko-prešovskej aglomerácie a je prirodzeným kultúrnym, hospodárskym, dopravným a administratívnym centrom regiónu Šariš.",
    "tatry": "Tatry (Prehrať slovenská výslovnosť) sú geomorfologický celok Fatransko-tatranskej oblasti a tvoria najvyššiu časť Karpát. Nachádzajú sa v severnej časti Slovenska na hranici s Poľskom. Pohorie sa rozprestiera na ploche 786 km², z toho na Slovensku 610 km². Ich alpský charakter zvýrazňuje 30 štítov a veží s výškou nad 2 500 m n. m.",
    "dunaj": "Dunaj (nem. Donau, chorv. Dunav, maď. Duna, srb. a bulh. Дунав, rum. Dunărea) je druhá najdlhšia európska rieka a najdlhšia rieka v Európskej únii. V meste Donaueschingen vzniká sútokom zdrojníc Breg a Brigach prameniacich vo Schwarzwalde (Nemecko), preteká južným Nemeckom, Rakúskom, Slovenskom, Maďarskom, Srbskom, potom tvorí po mnoho desiatok kilometrov rumunsko-bulharskú hranicu a ústi deltou do Čierneho mora na hraniciach medzi Rumunskom a Ukrajinou, pričom pri ukrajinskom meste Reni hraničí s teritóriom Moldavska.",
    "európa": "Európa je svetadiel, ktorý sa nachádza na severnej pologuli a vo východnej hemisfére. Pozostáva z najzápadnejších polostrovov kontinentálnej pevniny Eurázie, a hraničí so Severným ľadovým oceánom na severe, Atlantickým oceánom na západe, Stredozemným morom na juhu, a Áziou na východe. Európa sa bežne považuje za oblasť oddelenú od Ázie prostredníctvom povodia pohoria Ural, rieky Ural, Kaspického mora, Veľkého Kaukazu, Čierneho mora a vodných tokov Tureckej úžiny. Aj keď veľká časť tejto hranice presahuje pevninu, Európe sa všeobecne pripisuje štatút celého svetadiela pre jej veľkú fyzickú rozlohu a váhu histórie a tradícií.",
  "svet": "Svet môže byť: vo filozofii a podobne: v objektívnom ponímaní súbor všetkých (najmä hmotných) vecí, ktoré sú (t.j. v širšom zmysle vesmír a všetko prípadné ostatné, v užšom - staršom - zmysle Zem), resp. v subjektívnom ponímaní predstava o súbore všetkých vecí, ktoré sú (presná definícia ale závisí od autora), pozri svet (všetko),v kozmológii: vesmír,v bežnej komunikácii alebo v umeleckých textoch aj: Zem (resp. Zem so všetkým, čo na nej existuje),životný priestor ľudí,cudzina, najmä ďaleká; staršie aj len okolie, iný kraj,okruh ľudí s rovnakými záujmami; skupina jedincov rovnakého druhu,(všetci) ľudia, verejnosť,celkové pomery (života na Zemi alebo v jej časti), život, usporiadanie života (napr. stredoveký svet),uzavretá (najmä životná) oblasť, okruh, sféra,hviezdna sústava, planetárna sústava; nebeské teleso; galaxia.",
  "škola": "Škola je vo všeobecnosti akékoľvek výchovno-vzdelávacie zariadenie, organizácia alebo inštitúcia. Niekedy sa týmto pojmom myslí budova alebo sídlo danej inštitúcie. V užšom slova zmysle, na Slovensku, je škola inštitúcia zaradená do siete škôl a školských zariadení, ktoré majú oprávnenie uskutočňovať výchovu a vzdelávanie.",
    "stredná škola": "Stredná škola je výchovno-vzdelávacie zariadenie, ktoré poskytuje všeobecné a odborné vzdelanie s ucelenou sústavou potrebných vedomostí, spôsobilostí a zručností.",
      "vysoká škola": "Vysoká škola je vzdelávacia a vedecká inštitúcia na výchovu najvyššie kvalifikovaných odborníkov. Slovenský zákon o vysokých školách ju definuje ako „vrcholnú vzdelávaciu, vedeckú a umeleckú ustanovizeň“. Môže sa deliť na fakulty. „Poslaním vysokých škôl, ktoré sú súčasťou európskeho priestoru vysokoškolského vzdelávania a spoločného európskeho výskumného priestoru, je rozvíjať harmonickú osobnosť, vedomosti, múdrosť, dobro a tvorivosť v človeku a prispievať k rozvoju vzdelanosti, vedy, kultúry a zdravia pre blaho celej spoločnosti. Napĺňanie tohto poslania je predmetom hlavnej činnosti vysokých škôl“.",
    "univerzita": "Univerzita (z lat. universitas = všeobecnosť / (spoločenský) celok, kolégium) je pôvodne najstarší typ vysokej školy. Dnes univerzita spravidla môže byť označenie pre:(v západnej Európe a všeobecne) vedeckú vysokú školu poskytujúcu vzdelanie vo „všetkých“ oblastiach a deliacu sa na fakulty a/alebo pre vedeckú vysokú školu udeľujúcu aj najvyššie akademické tituly,(tradične najmä na Slovensku) vysokú školu, ktorá získala vyššiu akreditáciu ako ostatné vysoké školy, vyššiu úroveň vzdelania, dostatok kvalifikovaných profesorov a docentov, kvalitný proces výučby a pod. Nedokazuje zamerania škôl ale ich kvalitatívnu úroveň.(často v mnohých krajinách; na Slovensku od 90. rokov 20. stor.) akúkoľvek vysokú školu,(na Slovensku od roku 2002) univerzitnú vysokú školu, čiže vysokú školu poskytujúcu študijné programy všetkých troch stupňov s významným podielom 2. a 3. stupňa (pozri pod Vysoká škola); len tieto školy smú mať v názve slovo univerzita.",
    "učiteľ": "Učiteľ je kvalifikovaný, vzdelaný profesionálny pedagogický pracovník, ktorý sa zaoberá vyučovaním a vychovávaním žiakov.Predpokladom pre povolanie učiteľa sú jeho vlastné vedomosti a schopnosť predávať tieto ďalej žiakom. Niektoré učiteľské smery vyžadujú akreditáciu, podloženú skúškou a potvrdením o dostatočnej vedomostnej a schopnostnej úrovni učiteľa pre daný odbor. Druhy učiteľov: učiteľ v užšom zmysle: učiteľ na základnej škole, učiteľ na strednej škole (tradične nazývaný profesor*). vysokoškolský učiteľ:lektor**,asistent,odborný asistent,docent,profesor*,inštruktor. andragóg (lektor**):bežný lektor,tréner (rýchle odborné kurzy),facilitátor (psychoterapeutické kurzy),Vysvetlivka k * a **: Slová profesor a lektor majú, ako vidno, vždy dva rôzne významy.",
"študent":"Názov „študent“ pochádza zo stredoveku a pôvodne prislúchal študujúcim na univerzitách.Stredoškolský študent, Stredoškolský študent je fyzická osoba, ktorá splnila požiadavky prijímacieho riadenia (stanovené inštitúciou), bola prijatá na štúdium, zapísaná a vzdeláva sa v rámci študijného programu danej strednej školy.",
  "diplom": "Októbrový diplom (iné označenia: Cisársky diplom o úprave vnútorných štátoprávnych vzťahoch v monarchii, 20. október 1860, práv. označenie Cisársky diplom 226/1860…",
    "známka": "Známka môže byť: všeobecne: znak, prejav, svedectvo niečoho; príznak, náznak, charakteristický znak, prejav, malý predmet alebo značka na ustálené označenie niečoho, pozri napr. evidenčná známka, známka pre psa, ochranná známka. v pošte: skrátene: poštová známka, kolková známka (kolok). v školstve: stupeň ocenenia prospechu a správania žiaka, pozri známka (škola), v informatike: token, v ekonómii: skrátene obchodná známka, zriedkavo:značka (marketing)",
    "skúška": "Skúška je metóda, ktorá slúži na kontrolu výsledku (vzdelávania, výcviku, výpočtu).",
    "android": "Android je literárne a umelecké označenie umelo vytvorenej bytosti.. Android je stroj, ktorého účelom je správať sa, pracovať, poprípade myslieť ako človek. Názov „Android“ pochádza z gréckych výrazov andros (muž, človek) a -eides (rovnakého druhu, podobný). V literatúre, TV a filme sa táto definícia nedodržiava. Prví roboti vôbec, výrobky firmy R.U.R. zo rovnomenného románu Karla Čapka, boli androidi. Android Dat zo seriálu Star Trek bol robot. Robocop bol kyborg. Terminátor bol android. Okrem týchto existujú prípady, keď je ťažké rozhodnúť bez umelých kvót.",
    "iphone": "iPhone je rad smartphónov od firmy Apple Inc. iPhone je kombináciou mobilného telefónu, iPodu a moderného internetového zariadenia. Prvý iPhone predstavil bývalý riaditeľ spoločnosti Apple Inc. Steve Jobs 9. januára 2007 na konferencii Macworld Conference & Expo v San Franciscu. iPhone nemá zabudovanú klávesnicu, ovláda sa dotykovým displejom podobným PDA. Jeho operačný systém Apple označuje ako iOS (teda nie macOS, je však založený na rovnakom jadre ako štandardný Mac OS X). Prvý iPhone bol uvedený na americký trh v júni 2007 a neskôr tiež na trhy vo Spojenom kráľovstve, Nemecku, Francúzsku (všetky v r. 2007), v Írsku a Rakúsku sa dostal na trh v 2008.",
  "basketbal": "Basketbal je kolektívny šport, pri ktorom sa dve päťčlenné družstvá snažia dostať loptu do súperovho koša. Hrá sa na palubovke s dvoma košmi a je populárny po celom svete, najmä v USA a Európe.",
  "microsoft": "Microsoft je americká technologická spoločnosť, ktorú založil Bill Gates. Je známa najmä vďaka operačnému systému Windows a kancelárskemu balíku Microsoft Office, ktoré používajú milióny ľudí po celom svete.",
  "škoda": "Škoda Auto je český výrobca automobilov so sídlom v Mladej Boleslavi. Spoločnosť má dlhoročnú tradíciu a vyrába osobné vozidlá, ktoré sú obľúbené pre ich spoľahlivosť a dostupnosť.",
  "astronómia": "Astronómia je veda, ktorá sa zaoberá vesmírom, planétami, hviezdami a galaxiami. Študuje pohyby a vlastnosti nebeských telies a pomáha ľuďom porozumieť pôvodu a vývoju vesmíru.",
  "napoleon": "Napoleon Bonaparte bol francúzsky vojvodca a cisár, ktorý viedol mnohé vojny v Európe počas 19. storočia. Je známy svojimi vojenskými stratégiami a tiež tým, že výrazne ovplyvnil európske dejiny.",
  "android studio": "Android Studio je oficiálne vývojové prostredie (IDE) od Googlu, určené na tvorbu mobilných aplikácií pre operačný systém Android. Umožňuje programátorom písať kód v Jave, Kotlin či C++.",
  "marec": "Marec je tretí mesiac v roku podľa gregoriánskeho kalendára. Je známy ako mesiac, keď sa začína jar, dni sa predlžujú a príroda sa prebúdza po zime.",
  "vianoce": "Vianoce sú kresťanské sviatky, ktoré sa slávia 24. až 26. decembra a pripomínajú narodenie Ježiša Krista. Sú spojené s tradíciami ako darčeky, stromček, večera a rodinné stretnutia.",
  "wifi": "Wi-Fi je bezdrôtová technológia, ktorá umožňuje zariadeniam ako mobilné telefóny, notebooky alebo tablety pripájať sa k internetu bez použitia káblov, najčastejšie cez router.",
  "pizza": "Pizza je obľúbené jedlo talianskeho pôvodu, ktoré sa pripravuje z cesta, paradajkovej omáčky a syra, pričom sa na ňu môžu pridávať rôzne ďalšie suroviny ako šunka, zelenina, saláma či huby.",
  "láska": "Láska je silný emocionálny a psychologický vzťah medzi ľuďmi, ktorý sa prejavuje citovým putom, dôverou, porozumením a starostlivosťou. Môže byť romantická, priateľská, rodičovská alebo platonická.",
  "github": "GitHub je webová platforma pre verzovanie zdrojového kódu, kde vývojári ukladajú, spravujú a spolupracujú na projektoch. Využíva systém Git a je populárna najmä pri open-source vývoji.",
  "programovanie": "Programovanie je proces písania inštrukcií v špeciálnom jazyku (napr. JavaScript, Python), ktorými človek určuje, ako sa má správať počítač alebo aplikácia.",
  "auto": "Auto, známe aj ako automobil, je dopravný prostriedok určený na cestnú dopravu, ktorý poháňa motor. Umožňuje ľuďom a tovarom pohybovať sa nezávisle na dlhšie vzdialenosti.",
  "fyzika": "Fyzika je prírodná veda, ktorá skúma vlastnosti hmoty, energie a ich vzájomné pôsobenie. Patrí medzi základné vedy a je nevyhnutná pre pochopenie fungovania sveta.",
  "počítač": "Počítač je elektronické zariadenie, ktoré dokáže spracovávať dáta podľa presne definovaných inštrukcií. Používa sa na prácu, zábavu, komunikáciu a výskum.",
  "sloboda": "Sloboda znamená stav, keď má človek možnosť konať, vyjadrovať sa a rozhodovať podľa vlastnej vôle bez neoprávnených zásahov zvonka. Je to základná ľudská hodnota a právo.",
  "príroda": "Príroda zahŕňa všetko živé a neživé v našom prostredí, ako sú zvieratá, rastliny, rieky, hory, vzduch a klíma. Je nevyhnutná pre život a jej ochrana je kľúčová.",
  "youtube": "YouTube je najväčšia online platforma pre zdieľanie a pozeranie videí. Umožňuje používateľom nahrávať, komentovať a sledovať videá v rôznych kategóriách ako hudba, vzdelávanie či zábava.",
  "čas": "Čas je základná fyzikálna veličina, ktorá vyjadruje trvanie udalostí a poradie ich nasledovania. V každodennom živote ho meriame pomocou hodín, kalendárov a harmonogramov.",
 "zem": "Zem je tretia planéta slnečnej sústavy a jediné známe miesto vo vesmíre, kde existuje život. Má tvar takmer guľového telesa a je zložená z jadra, plášťa a kôry. Na povrchu sa nachádzajú kontinenty, oceány, atmosféra a život v rôznych formách.",
"mlieko": "Mlieko je biela tekutina produkovaná mliečnymi žľazami cicavcov. U ľudí je dôležitým výživovým produktom, bohatým na vápnik, bielkoviny a vitamíny. Používa sa na pitie aj pri výrobe jogurtov, syrov a ďalších potravín.",
"január": "Január je prvý mesiac v roku podľa gregoriánskeho kalendára. Je to typicky zimný mesiac na severnej pologuli, kedy sa oslavuje Nový rok a pre mnohých je symbolom nových začiatkov.",
"tlačiareň": "Tlačiareň je zariadenie, ktoré prevádza digitálne dokumenty alebo obrázky do fyzickej formy, najčastejšie na papier. Existujú atramentové, laserové aj 3D tlačiarne. Používa sa v domácnostiach, školách aj kanceláriách.",
"voda": "Voda je chemická zlúčenina pozostávajúca z dvoch atómov vodíka a jedného atómu kyslíka (H₂O). Je nevyhnutná pre život, tvorí väčšinu telesnej hmotnosti živej bytosti a pokrýva približne 71 % povrchu Zeme.",
"učebnica": "Učebnica je kniha vytvorená na účely výučby. Obsahuje systematicky usporiadané informácie, ktoré pomáhajú žiakom a študentom pochopiť a zvládnuť učivo v danom predmete alebo odbore.",
"google": "Google je technologická spoločnosť známa najmä svojím internetovým vyhľadávačom. Založili ju Larry Page a Sergey Brin v roku 1998. Dnes ponúka množstvo služieb ako Gmail, YouTube, Google Maps a Android.",
"história": "História je veda, ktorá skúma minulosť ľudskej civilizácie. Analyzuje udalosti, osobnosti, spoločenské zmeny a kultúry. Pomáha nám pochopiť vývoj ľudstva a poučiť sa z minulých skúseností.",
"vesmír": "Vesmír je nekonečný priestor, ktorý zahŕňa všetko existujúce — galaxie, hviezdy, planéty, čas a hmotu. Začal sa veľkým treskom pred približne 13,8 miliardami rokov a neustále sa rozpína.",
"mobil": "Mobil, resp. mobilný telefón, je prenosné zariadenie určené na komunikáciu, písanie správ, prístup na internet a spúšťanie aplikácií. V dnešnej dobe ide najmä o smartfóny s dotykovým displejom a operačným systémom.",
"facebook": "Facebook je sociálna sieť založená Markom Zuckerbergom v roku 2004. Umožňuje používateľom zdieľať príspevky, fotografie, videá a komunikovať s priateľmi. Je jednou z najväčších platforiem na svete s miliardami aktívnych používateľov mesačne.",
"autobus": "Autobus je dopravný prostriedok určený na prepravu väčšieho počtu osôb. Jazdí po stanovených trasách a je bežne používaný v mestskej aj medzimestskej hromadnej doprave.",
"robot": "Robot je stroj alebo zariadenie navrhnuté na vykonávanie úloh, ktoré môžu byť manuálne, automatické alebo programovateľné. Využíva sa v priemysle, domácnosti aj vedeckom výskume.",
"júl": "Júl je siedmy mesiac v roku podľa gregoriánskeho kalendára. Je to typicky letný mesiac na severnej pologuli, spojený s dovolenkami, teplým počasím a letnými prázdninami.",
"čítanie": "Čítanie je proces vnímania a interpretácie písaného textu. Pomáha rozvíjať slovnú zásobu, myslenie, predstavivosť a je základným prvkom vzdelávania.",
"počítač1": "Počítač je elektronické zariadenie určené na spracovanie informácií. Používa sa na prácu, štúdium, zábavu aj komunikáciu. Skladá sa z hardvéru a softvéru.",
"zdravie": "Zdravie je stav fyzickej, psychickej a sociálnej pohody. Je ovplyvňované stravou, pohybom, spánkom, stresom aj genetickými faktormi. Je jednou z najcennejších hodnôt v živote človeka.",
"žiak": "Žiak je osoba zapísaná na školu, ktorá sa zúčastňuje vyučovania a získava vedomosti, zručnosti a návyky. Môže ísť o žiaka základnej, strednej alebo aj inej vzdelávacej inštitúcie.",
"wifi router": "Wi-Fi router je zariadenie, ktoré sprostredkúva bezdrôtové pripojenie na internet. Pripája sa na modem a vytvára Wi-Fi signál, ktorý môžu používať viaceré zariadenia naraz.",
"november": "November je jedenásty mesiac roka a na severnej pologuli je typicky jesenný. Je známy Sviatkom všetkých svätých, pamätnými udalosťami ako Deň boja za slobodu a demokraciu a prípravami na zimné obdobie.",
"youtube": "YouTube je najväčšia platforma na zdieľanie videí na svete, ktorú v roku 2005 založili traja bývalí zamestnanci PayPalu. Umožňuje sledovať, nahrávať a komentovať videá v rôznych kategóriách ako hudba, vzdelávanie, vlogy či hry.",
"hokej": "Hokej je rýchla kolektívna hra na ľade, kde sa hráči snažia pomocou hokejky dopraviť puk do brány súpera. Je jedným z najobľúbenejších zimných športov, najmä v krajinách ako Kanada, Slovensko či Rusko.",
"spotify": "Spotify je digitálna hudobná služba, ktorá umožňuje streamovať milióny skladieb, podcastov a playlistov. Bola založená v roku 2006 a patrí medzi najpopulárnejšie platformy na počúvanie hudby na svete.",
"obec": "Obec je základná územná samosprávna jednotka na Slovensku. Môže zahŕňať jednu alebo viac osád či miestnych častí a má vlastného starostu a obecné zastupiteľstvo.",
"auto": "Auto (automobil) je motorové vozidlo určené na osobnú alebo nákladnú prepravu. Je neoddeliteľnou súčasťou moderného života a výrazne ovplyvňuje dopravu, priemysel aj životné prostredie.",
"príroda": "Príroda zahŕňa všetky živé a neživé zložky planéty Zem – od rastlín, zvierat, lesov až po hory, rieky a klímu. Je zdrojom života, inšpirácie aj oddychu pre ľudí.",
"gmail": "Gmail je e-mailová služba od spoločnosti Google. Ponúka veľkú kapacitu úložiska, inteligentné filtrovanie a jednoduché prepojenie s inými Google službami ako Drive, Kalendár či Meet.",
"futbalista": "Futbalista je profesionálny alebo amatérsky hráč futbalu. Trénuje techniku, fyzickú kondíciu a taktiku, aby podával čo najlepší výkon v zápasoch a súťažiach.",
"učebnica": "Učebnica je kniha určená na výučbu určitého predmetu. Obsahuje teoretické poznatky, príklady a úlohy a je bežnou súčasťou vzdelávacieho procesu v školách.",
"banka": "Banka je finančná inštitúcia, ktorá poskytuje služby ako správa účtov, úvery, hypotéky, vklady a platby. Zohráva dôležitú úlohu v ekonomike a finančnom systéme štátu.",
  "počítač": "Počítač je elektronické zariadenie, ktoré slúži na spracovanie údajov a vykonávanie výpočtov. Používa sa v rôznych oblastiach – od kancelárskej práce cez hranie hier až po programovanie a vedecký výskum.",
  "základná škola": "Základná škola je typ školy, ktorú deti navštevujú po predškolskom veku. Poskytuje základné vzdelanie v čítaní, písaní, matematike a ďalších predmetoch, zvyčajne od 1. do 9. ročníka.",
  "sloboda": "Sloboda je stav, keď má človek možnosť rozhodovať sa, konať a myslieť podľa vlastného presvedčenia bez vonkajšieho nátlaku. Je základnou hodnotou demokracie a ľudských práv.",
  "vojna": "Vojna je ozbrojený konflikt medzi štátmi, skupinami alebo národmi. Prináša zničenie, utrpenie a často veľké politické či územné zmeny. V dejinách ľudstva mala vojna zásadný vplyv na vývoj civilizácií.",
  "mier": "Mier je opakom vojny – stav bez násilia a ozbrojených konfliktov, keď spoločnosti spolupracujú, obchodujú a žijú pokojne. Mier je cieľom mnohých medzinárodných organizácií.",
  "robot": "Robot je stroj schopný vykonávať úlohy automaticky alebo na základe pokynov. Môže byť fyzický (napr. priemyselný robot v továrni) alebo virtuálny (napr. softvérový bot).",
  "programovanie": "Programovanie je proces tvorby počítačových programov pomocou špeciálnych jazykov ako Python, Java alebo C. Programátor píše kód, ktorým určuje správanie aplikácie alebo systému.",
  "slnko": "Slnko je hviezda v strede našej slnečnej sústavy. Je najbližšou hviezdou k Zemi a zabezpečuje svetlo a teplo, ktoré sú nevyhnutné pre život na planéte.",
  "vesmír": "Vesmír je nekonečný priestor, ktorý zahŕňa všetky planéty, hviezdy, galaxie a hmotu. Je predmetom skúmania astronómie a kozmológie. Vznikol pravdepodobne veľkým treskom pred približne 13,8 miliardami rokov.",
  "kniha": "Kniha je súbor stránok obsahujúcich text alebo obrázky, ktoré sú zviazané dohromady. Môže byť náučná, beletristická, technická alebo umelecká. Slúži na vzdelávanie, zábavu aj uchovávanie vedomostí.",
"mobilný telefón": "Mobilný telefón, často nazývaný mobil, je prenosné zariadenie umožňujúce telefonovanie, posielanie správ a v prípade smartfónov aj pripojenie na internet, fotografovanie, navigáciu, počúvanie hudby a spúšťanie rôznych aplikácií. Je základným nástrojom modernej komunikácie.",
  "internet": "Internet je globálna sieť, ktorá prepája milióny počítačov a iných zariadení na celom svete. Umožňuje výmenu informácií, komunikáciu, zdieľanie súborov, online nakupovanie, prístup k vzdelaniu a zábave. Je základom moderného digitálneho sveta.",
   "instagram": "Instagram je sociálna sieť zameraná na zdieľanie fotografií a videí. Založená bola v roku 2010 a neskôr ju kúpil Facebook. Užívatelia tu môžu zverejňovať príspevky, príbehy (stories), reels a komunikovať prostredníctvom správ.",
  "snapchat": "Snapchat je mobilná aplikácia, ktorá umožňuje posielanie krátkych správ vo forme fotiek a videí, ktoré po zhliadnutí zmiznú. Je populárna najmä medzi mladými ľuďmi a obsahuje funkcie ako filtre, príbehy, mapy priateľov a hry.",
  "tiktok": "TikTok je krátkofomátová video platforma, kde používatelia nahrávajú 15–60 sekundové videá často s hudbou, efektmi a výzvami. Vznikol v Číne ako Douyin, neskôr zjednotený pod názvom TikTok. Má obrovský vplyv na popkultúru a trendy.",
  "chatbot": "Chatbot je počítačový program navrhnutý na komunikáciu s ľuďmi cez text alebo hlas. Používa sa v zákazníckych službách, aplikáciách, webových stránkach alebo ako asistent (napr. ErikAI, ChatGPT, Siri). Môže byť jednoduchý alebo inteligentný s umelou inteligenciou.",
  "emoji": "Emoji sú malé piktogramy, ktoré sa používajú v online komunikácii na vyjadrenie emócií, objektov, činností alebo symbolov. Pochádzajú z Japonska a stali sa globálnym jazykom, ktorý dopĺňa text a pomáha vyjadriť náladu alebo význam.",
  "robot": "Robot je stroj alebo systém, ktorý je schopný vykonávať určité úlohy samostatne alebo podľa programovania. Môže byť priemyselný (napr. vo výrobe áut), domácnosti (napr. robotický vysávač) alebo výskumný (napr. vesmírne sondy). Niektoré roboty majú tvar podobný človeku – tzv. androidi.",
  "počítač": "Počítač je elektronické zariadenie, ktoré slúži na spracovanie dát a vykonávanie výpočtov. Môže byť stolový, prenosný (notebook), alebo mini (napr. Raspberry Pi). Využíva sa na prácu, zábavu, programovanie, komunikáciu aj tvorbu obsahu.",
  "notebook": "Notebook je prenosný počítač, ktorý kombinuje funkcie stolného počítača s možnosťou mobilného používania. Obsahuje displej, klávesnicu, batériu a všetko potrebné v jednom kompaktnom zariadení. Je vhodný na školu, prácu aj cestovanie.",
  "kódovanie": "Kódovanie je proces vytvárania počítačových programov pomocou programovacieho jazyka, ako je napríklad Python, Java, C alebo HTML. Slúži na vytváranie webových stránok, aplikácií, hier a iných digitálnych systémov. Základom je logika a kreativita.",
  "hra": "Hra je činnosť vykonávaná pre zábavu, potešenie alebo rozvoj schopností. Môže byť fyzická (napr. futbal), stolová (napr. šach), alebo digitálna (napr. počítačové hry). Hry často obsahujú pravidlá, cieľ a prvok súťaže alebo spolupráce.",
  "hračka": "Hračka je predmet určený na hru, najmä pre deti. Môže to byť plyšové zvieratko, stavebnica, autíčko, bábika alebo elektronická hra. Hračky rozvíjajú detskú fantáziu, jemnú motoriku, logické myslenie a sociálne schopnosti.",
  "vesmír": "Vesmír je nekonečný priestor, v ktorom sa nachádzajú planéty, hviezdy, galaxie a ďalšie nebeské telesá. Je predmetom výskumu astronómie a kozmológie. Obsahuje miliardy galaxií a vznikol podľa teórie veľkého tresku pred približne 13,8 miliardami rokov.",
  "mesiac": "Mesiac je prirodzená družica Zeme, ktorá obieha okolo našej planéty približne raz za 29,5 dňa. Má vplyv na príliv a odliv oceánov a je jediným mimozemským telesom, kde človek fyzicky pristál – misia Apollo 11 v roku 1969.",
  "slnko": "Slnko je hviezda v strede slnečnej sústavy, ktorá zabezpečuje svetlo a teplo potrebné pre život na Zemi. Má priemer približne 1,39 milióna km a tvorí ho prevažne vodík a hélium. Jeho energia vzniká jadrovou fúziou v jadre.",
  "planéta": "Planéta je veľké nebeské teleso, ktoré obieha hviezdu a má dostatočnú hmotnosť na to, aby bola jej gravitácia vyvážená do guľovitého tvaru. V našej slnečnej sústave je osem planét – medzi nimi Zem, Mars, Jupiter, Saturn a ďalšie."
    "trenčín": "Trenčín je krajské mesto na západnom Slovensku, známe svojím hradom na brale nad riekou Váh.",
"trnava": "Trnava je starobylé mesto prezývané slovenský Rím vďaka množstvu kostolov.",
"martin": "Martin je kultúrne a historické centrum Slovenska, známe Matica slovenská a Slovenským národným múzeom.",
"poprad": "Poprad leží pod Vysokými Tatrami a je vstupnou bránou do tejto oblasti.",
"prievidza": "Prievidza je mesto v Hornonitrianskom regióne známe najmä baníctvom.",
"zvolen": "Zvolen je historické mesto so Zvolenským zámkom a významným železničným uzlom.",
"michalovce": "Michalovce ležia v regióne Zemplín neďaleko Zemplínskej šíravy.",
"levice": "Levice sú juhoslovenské mesto známe Levickým hradom a poľnohospodárstvom.",
"komárno": "Komárno je pohraničné mesto na Dunaji, známe pevnôstkou a multikultúrnym prostredím.",
"liptovský mikuláš": "Liptovský Mikuláš je mesto v regióne Liptov, blízko Liptovskej Mary a Nízkych Tatier.",
"ružomberok": "Ružomberok leží medzi Malou a Veľkou Fatrou, známy aj papierenským priemyslom.",
"topoľčany": "Topoľčany je mesto v Nitrianskom kraji známe potravinárskym a strojárskym priemyslom.",
"považská bystrica": "Považská Bystrica je priemyselné mesto v doline rieky Váh.",
"spišská nová ves": "Spišská Nová Ves leží pri Slovenskom raji a má najvyššiu kostolnú vežu na Slovensku.",
"humenné": "Humenné je mesto na východe Slovenska s kaštieľom a múzeom.",
"senica": "Senica je priemyselné a športové mesto v západnej časti Slovenska.",
"vranov nad toplou": "Vranov nad Topľou je okresné mesto východne od Prešova.",
"nové zámky": "Nové Zámky sú južné mesto s historickým centrom a pevnosťou.",
"trebišov": "Trebišov je vinárske a poľnohospodárske mesto na juhovýchodnom Slovensku.",
"pezinok": "Pezinok je vinohradnícke mesto pri Bratislave, známe Malokarpatským vinobraním.",
"malacky": "Malacky sú mesto na Záhorí, blízko hraníc s Rakúskom.",
"skalica": "Skalica je historické mesto známe trdelníkom a barokovou architektúrou.",
"senec": "Senec je rekreačné mesto známe Slnečnými jazerami.",
"rožňava": "Rožňava je gemerské mesto s baníckou tradíciou a krásnym historickým námestím.",
"bánovce nad bebravou": "Bánovce nad Bebravou je menšie priemyselné mesto v Trenčianskom kraji.",
"lučenec": "Lučenec je centrum Novohradu, známe historickými pamiatkami a parkom.",
"detva": "Detva je známa folklórom, leží pod Poľanou a každoročne hostí folklórne slávnosti.",
"rimavská sobota": "Rimavská Sobota je okresné mesto na juhu stredného Slovenska.",
"partizánske": "Partizánske je mladé mesto s bohatou obuvníckou tradíciou.",
"handlová": "Handlová je banícke mesto v Hornonitrianskom regióne.",
"šamorín": "Šamorín je viacjazyčné mesto v blízkosti Dunaja, známe hipodrómom a športovým areálom.",
"šurany": "Šurany ležia v Podunajskej nížine, známe poľnohospodárstvom.",
"holíč": "Holíč je mesto s barokovým zámkom a tradíciou keramickej výroby.",
"stará ľubovňa": "Stará Ľubovňa je historické mesto pod Tatrami so zachovaným hradom.",
"kežmarok": "Kežmarok je mesto s krásnym historickým centrom a dreveným artikulárnym kostolom.",
"čadca": "Čadca je centrum regiónu Kysuce, známe folklórom a kopaničiarskou kultúrou.",
"tvrdošín": "Tvrdošín je oravské mesto známe dreveným kostolom zapísaným v UNESCO.",
"námestovo": "Námestovo je pri Oravskej priehrade a je centrom horného Liptova.",
"bytča": "Bytča je malé historické mesto s renesančným zámkom.",
"turzovka": "Turzovka je mestečko na Kysuciach známe pútnickym miestom Živčáková.",
"brusno": "Brusno je obec s kúpeľmi pri Banskej Bystrici.",
"rajec": "Rajec je malé mestečko známe kúpeľmi Rajec a pekným historickým centrom.",
"bojnice": "Bojnice sú známe kúpeľmi, zámkom a ZOO.",
"modra": "Modra je vinohradnícke mesto, rodisko Ľudovíta Štúra.",
"sliač": "Sliač je kúpeľné mesto medzi Zvolenom a Banskou Bystricou.",
"žiarnadhronom": "Žiar nad Hronom je priemyselné mesto pri rieke Hron.",
"turčianske teplice": "Turčianske Teplice sú známe kúpeľmi s liečivou vodou.",
"vrútky": "Vrútky sú menšie mesto pri Martine s významnou železničnou križovatkou.",
"velky krtis": "Veľký Krtíš je mesto na juhu stredného Slovenska s poľnohospodárskym charakterom.",
"sobotište": "Sobotište je obec v okrese Senica, známa históriou habánov a vinohradníctvom.",
"dojč": "Dojč je obec v Záhorskej nížine, leží medzi Senicou a Trnavou.",
"krutá": "Krušovce je obec v okrese Topoľčany, známa poľnohospodárstvom a lokalitou Topoľčianska dolina.",
"ružindol": "Ružindol je vinohradnícka obec v blízkosti Trnavy.",
"smolenice": "Smolenice sú známe Smolenickým zámkom a jaskyňami Malých Karpát.",
"častá": "Častá je obec pod hradom Červený Kameň a má bohatú vinohradnícku tradíciu.",
"budmerice": "Budmerice sú známe kaštieľom, kde pôsobia spisovatelia a umelci.",
"hreňov": "Hreňov je obec pri Leviciach, situovaná v poľnohospodárskej oblasti.",
"beluša": "Beluša je veľká obec medzi Púchovom a Považskou Bystricou.",
"závod": "Závod je obec na Záhorí, neďaleko Malaciek.",
"čachtice": "Čachtice sú známe hradom Čachtice a legendou o Alžbete Báthory.",
"bošáca": "Bošáca je kopaničiarska obec pri Novom Meste nad Váhom, známa slivovicou.",
"jaslovské bohunice": "Obec známa atómovou elektrárňou, nachádza sa pri Trnave.",
"radvaň nad dunajom": "Obec na juhu Slovenska pri Komárne, známa dunajským prostredím.",
"lipany": "Lipany sú malé mesto v okrese Sabinov na východnom Slovensku.",
"plavnica": "Plavnica je obec pri Starej Ľubovni, blízko poľských hraníc.",
"hronovce": "Hronovce sú obec v okrese Levice, ležiaca pri rieke Hron.",
"šahy": "Šahy sú pohraničné mesto pri maďarskej hranici s kúpeľnou tradíciou.",
"tornaľa": "Tornaľa je mesto v okrese Revúca s maďarskou menšinou.",
"fiľakovo": "Fiľakovo je známe zrúcaninou hradu a pestrou kultúrou.",
"poltár": "Poltár je mesto známe sklárskou výrobou a prírodným okolím.",
"muráň": "Muráň je obec pri NP Muránska planina, známa hradom a chovom koní.",
"jelšava": "Jelšava je banícke mesto v okrese Revúca.",
"revúca": "Revúca je menšie mesto na Gemeri, známe národnými dejinami.",
"tvrdošovce": "Tvrdošovce sú obec s bohatou poľnohospodárskou históriou.",
"zlaté moravce": "Zlaté Moravce sú priemyselné mesto medzi Nitrou a Žarnovicou.",
"žiarske podhradie": "Malá obec pri Žiari nad Hronom, historicky spojená s hradom Šášov.",
"kláštor pod znievom": "Obec známa národno-obrodeneckým významom a školstvom.",
"močenok": "Močenok je obec v Nitrianskom kraji so silnou katolíckou tradíciou.",
"šintava": "Šintava je historická obec pri Seredi s bývalým hradom a cukrovarom.",
"semerovo": "Semerovo je obec v Novozámockom okrese s typickou nížinnou krajinou.",
"zemné": "Zemné je obec na juhu Slovenska pri Váhu s maďarským obyvateľstvom.",
"jablonica": "Jablonica je obec so zámkom a tradíciou ovocinárstva.",
"bátorove kosihy": "Bátorove Kosihy sú obec na juhu Slovenska s maďarskou komunitou.",
"šurany": "Šurany sú menšie mesto s históriou a cukrovarníckou tradíciou.",
"veľké kapušany": "Veľké Kapušany sú pohraničné mesto pri ukrajinskej hranici.",
"sobrance": "Sobranec je malé mesto východne od Michaloviec.",
"kráľovský chlmec": "Mesto na juhovýchodnom Slovensku s prevažne maďarským obyvateľstvom.",
"veľký lapáš": "Veľký Lapáš je obec pri Nitre s historickými koreňmi.",
"janík": "Janík je obec v okrese Košice-okolie, známa vinicami.",
"jasenov": "Jasenov je obec pri Humennom so zrúcaninou hradu.",
"klenovec": "Klenovec je obec na juhu stredného Slovenska, folklórne aktívna.",
"valaská": "Valaská je obec pri Brezne s blízkosťou Nízkych Tatier.",
"poniky": "Poniky sú obec v stredoslovenskom regióne známej tradíciami a architektúrou.",
"tŕnie": "Tŕnie je malá obec v okrese Zvolen, typická dedinskou architektúrou.",
"dobrá niva": "Dobrá Niva je obec známa zámkom a remeselnými trhmi.",
"prudniky": "Prudniky je obec v okrese Rožňava v okolí Volovských vrchov.",
"košťany nad turcom": "Košťany sú pri Martine, známe súčasnou výstavbou a výhľadmi na pohoria.",
"turčianska štiavnička": "Turčianska Štiavnička je obec so známym parkom a alejou stromov.",
"lúčky": "Lúčky sú kúpeľná obec v Liptove s termálnymi prameňmi.",
    "liptovská teplička": "Liptovská Teplička je horská obec v okrese Poprad, známa ľudovou architektúrou a zemiakovými pivnicami.",
"hybe": "Hybe je obec v Liptove, známa literárnou tradíciou a krásnou polohou pri Kriváni.",
"východná": "Východná je obec známa najväčším folklórnym festivalom na Slovensku.",
"liptovský hrádok": "Liptovský Hrádok je malé mesto s hradom a významným lesníckym školstvom.",
"važec": "Važec je obec na úpätí Tatier, známa svojimi krojmi a folklórom.",
"zuberec": "Zuberec je obec v Roháčoch, známa múzeom oravskej dediny a lyžovaním.",
"habovka": "Habovka je obec v Západných Tatrách, tradičná oravská obec.",
"oravský podzámok": "Oravský Podzámok je známy vďaka Oravskému hradu, jednému z najkrajších na Slovensku.",
"námestovo": "Námestovo je centrum severnej Oravy pri Oravskej priehrade.",
"trstená": "Trstená je mesto blízko poľských hraníc s historickým námestím.",
"lokca": "Lokca je väčšia obec na Orave, známa folklórom a tradičnou kultúrou.",
"sihelné": "Sihelné je obec pri hranici s Poľskom s bohatou drevenou architektúrou.",
"rabča": "Rabča je oravská obec známa zachovalým folklórom a silným náboženským životom.",
"klin": "Klin je obec, kde sa nachádza najväčšia socha Ježiša Krista na Slovensku.",
"mutné": "Mutné je malá horská obec pri hraniciach s Poľskom.",
"slaná lehota": "Slaná Lehota je dedinka pri Detve, obklopená krásnou prírodou.",
"detva": "Detva je centrum folklóru Podpoľania, známa slávnosťami a fujarami.",
"hradná": "Hradná je menšia obec pri Považskej Bystrici.",
"ladce": "Ladce sú známe cementárňou a nachádzajú sa v Ilavskom okrese.",
"beluša": "Beluša je rozvinutá obec medzi Púchovom a Ilavou.",
"ilava": "Ilava je mesto so známou väznicou a bohatou históriou.",
"bošany": "Bošany sú obec s kaštieľom a kostolom z románskeho obdobia.",
"partizánske": "Partizánske je mesto založené Baťom ako Baťovany, významné priemyselné centrum.",
"veľké ulože": "Veľké Ulože sú obec pri Levoči s krásnou prírodou.",
"spisská bela": "Spišská Belá je mesto pri Tatrách s historickým centrom a Múzeom J. M. Petzvala.",
"hrabušice": "Hrabušice sú vstupnou bránou do Slovenského raja – Prielom Hornádu.",
"dedinky": "Dedinky sú rekreačné stredisko pri Palcmanskej Maši v Slovenskom raji.",
"stratená": "Stratená je obec v Slovenskom raji s turistickými možnosťami.",
"dobšiná": "Dobšiná je mesto pri NP Slovenský raj, známe Dobšinskou ľadovou jaskyňou.",
"rožňava": "Rožňava je okresné mesto v Gemeri s historickým jadrom.",
"betliar": "Betliar je známy nádherným kaštieľom s anglickým parkom.",
"krásnohorské podhradie": "Obec pod hradom Krásna Hôrka, s pamätníkom Andrássyovcov.",
"mlynky": "Mlynky sú horská obec vhodná na zimné aj letné športy.",
"telgárt": "Telgárt je obec pod Kráľovou hoľou, pri sútoku Hrona.",
"heľpa": "Heľpa je známa Heľpianskymi slávnosťami a ľudovým umením.",
"polomka": "Polomka leží v horehronskom regióne, má bohatú tradíciu a folklór.",
"čierny balog": "Čierny Balog je známy lesnou železničkou a hustými lesmi.",
"hronec": "Hronec je obec v doline Hrona, spojená s hutníctvom.",
"brezno": "Brezno je stredoslovenské mesto pri Nízkych Tatrách s historickým centrom.",
"bystrá": "Bystrá je obec pri Táľoch, známa jaskyňou a lyžiarskym areálom.",
"mýto pod ďumbierom": "Lyžiarske a rekreačné stredisko pod Nízkymi Tatrami.",
"horná lehota": "Horná Lehota je podhorská obec blízko Táľov a Dolnej Lehoty.",
"dolná lehota": "Dolná Lehota je pokojná dedina v prírode Horehronia.",
"závadka nad hronom": "Závadka nad Hronom je rozvinutá obec pri rieke Hron.",
"valaská dubová": "Valaská Dubová je obec známa zbojníckymi legendami o Jurajovi Jánošíkovi.",
"likavka": "Likavka je obec pri Ružomberku, známa zrúcaninou hradu Likava.",
"lisková": "Lisková je obec pri Ružomberku s archeologickým náleziskom – Liskovskou jaskyňou.",
"lúčky kúpele": "Lúčky sú kúpeľná obec s liečivými minerálnymi prameňmi a vodopádom.",
"turany": "Turany sú mesto pri Martine s výhľadom na Kriváň.",
"vrútky": "Vrútky sú železničné a priemyselné mestečko susediace s Martinom.",
    "martin": "Martin je významné mesto na severe Slovenska, známe svojou kultúrnou a národnou históriou.",
"blatnica": "Blatnica je obec pod Veľkou Fatrou, známa hradom Blatnica a turistikou v Gaderskej doline.",
"mošovce": "Mošovce sú rodiskom Jána Kollára a známe krásnym parkom a kúriou.",
"turčianske teplice": "Turčianske Teplice sú kúpeľné mesto s liečivou termálnou vodou.",
"kláštor pod znievom": "Obec so silnou národnou históriou a blízkosťou Znievskeho hradu.",
"kremnica": "Kremnica je historické banícke mesto s mincovňou a krásnym námestím.",
"šturec": "Šturec je horská obec v Kremnických vrchoch, pri známej Šturcianskej tiesňave.",
"turecká": "Turecká je známa lyžiarskym areálom a tradičnými fašiangovými oslavami.",
"staré hory": "Staré Hory sú významné pútnické miesto s krásnym kostolom a kalváriou.",
"donovaly": "Donovaly sú populárne lyžiarske a rekreačné stredisko medzi Tatrami a Veľkou Fatrou.",
"banská bystrica": "Banská Bystrica je krajské mesto so silnou historickou a kultúrnou tradíciou.",
"zvolen": "Zvolen je mesto so zámkom a priemyselnou tradíciou na strednom Slovensku.",
"sliač": "Sliač je kúpeľné mesto s letiskom a bohatou históriou.",
"kováčová": "Kováčová je obec pri Zvolene, známa rehabilitačným ústavom a termálnym kúpaliskom.",
"detva": "Detva je podpoľanské mesto známe folklórom a výrobou fujár.",
"zvolenská slatina": "Obec v Podpoľaní so silnou partizánskou históriou.",
"vígľaš": "Vígľaš je obec s kaštieľom a bohatou históriou v Poľane.",
"dobrá niva": "Dobrá Niva je obec s gotickým kostolom a zrúcaninou hradu.",
"krupina": "Krupina je malé historické mesto známe svojou strážnou vežou – vartovkou.",
"bzovík": "Bzovík je obec so zrúcaninou kláštorného opevnenia.",
"hontianske tesáre": "Obec pri Dudinciach, známa tradičným vinohradníctvom.",
"dudince": "Dudince sú kúpeľné mesto známe liečivou vodou na pohybové ústrojenstvo.",
"levice": "Levice sú mesto na juhu Slovenska s hradom a priemyslom.",
"tlmače": "Tlmače sú obec s elektrárňou a technickým zázemím.",
"želiezovce": "Želiezovce sú mesto známe Františkom Schubertom, ktorý tu pôsobil.",
"šahy": "Šahy sú pohraničné mesto s maďarskou komunitou a historickými stavbami.",
"nová baňa": "Nová Baňa je banské mestečko pri Pohronskom Inovci.",
"hliník nad hronom": "Obec pri Žiari nad Hronom, známa hutníckym priemyslom.",
"žiarnad hronom": "Žiar nad Hronom je mesto v strednom Pohroní s priemyselnou tradíciou.",
"ladomerská vieska": "Obec susediaca so Žiarom, administratívne s ním spojená.",
"ošťadnica": "Oščadnica je známe lyžiarske a turistické stredisko v Kysuciach.",
"nová bystrica": "Nová Bystrica je horská obec s vodnou nádržou Nová Bystrica.",
"stará bystrica": "Stará Bystrica je známa orlojom – najpresnejším na Slovensku.",
"radôstka": "Radôstka je kysucká obec obklopená horami a tradíciami.",
"zborov nad bystricou": "Zborov nad Bystricou je obec pri Krásne nad Kysucou.",
"krásno nad kysucou": "Krásno je mesto známe železničnou križovatkou a folklórom.",
"kysucké nové mesto": "Kysucké Nové Mesto je priemyselné a kultúrne centrum Kysúc.",
"čadca": "Čadca je okresné mesto na severe Slovenska, dôležité dopravné uzol.",
"skalité": "Skalité je pohraničná obec so železničným priechodom do Poľska.",
"svrčinovec": "Svrčinovec je obec v Kysuciach pri hranici s Českom a Poľskom.",
"korňa": "Korňa je obec známa prírodným ropným prameňom – jediným na Slovensku.",
"makov": "Makov je pohraničná obec s výbornými podmienkami na lyžovanie.",
"turzovka": "Turzovka je známe pútnické miesto s kalváriou Živčáková.",
"klokočov": "Klokočov je horská obec neďaleko Turzovky.",
"radoľa": "Radoľa je obec s kaštieľom, patriacim medzi najstaršie zachované stavby na Kysuciach.",
"radola": "Radola – alternatívny zápis tej istej obce, pre kontrolu výskytu.",
"lutiše": "Lutiše sú malebná obec s tradičnou architektúrou na Kysuciach.",
"terchová": "Terchová je rodisko Juraja Jánošíka a známe centrum folklóru a turistiky.",
"belá (žilina)": "Belá je obec pri Terchovej, často navštevovaná turistami do Vrátnej doliny.",
"strečno": "Strečno je známe svojím hradom nad Váhom a kompom cez rieku.",
    "necpaly": "Necpaly sú obec v Turci s historickým kaštieľom a pekným okolím na turistiku.",
"folkušová": "Folkušová je malá tichá obec pri Martine s tradičnými domami.",
"sučany": "Sučany sú obec s gymnáziom, známym aj v minulosti, pri Martine.",
"turany": "Turany sú menšie mesto s výhodnou polohou medzi horami.",
"vrútky": "Vrútky sú železničným uzlom a prímestskou časťou Martina.",
"košťany nad turcom": "Košťany sú dedinka pri Martine s pekným výhľadom na Veľkú Fatru.",
"príbovce": "Príbovce sú obec pri Martine, známe archeologickým náleziskom.",
"blatnická dolina": "Blatnická dolina je turisticky obľúbená časť Veľkej Fatry.",
"jaseňová": "Jaseňová je malá dedina na Orave pri Dolnom Kubíne.",
"oravský podzámok": "Oravský Podzámok je obec pod známym Oravským hradom.",
"dolný kubín": "Dolný Kubín je okresné mesto na Orave s kultúrnou tradíciou.",
"zuberec": "Zuberec je obec známa skanzenom a blízkosťou Západných Tatier.",
"habovka": "Habovka je obec s bohatou folklórnou tradíciou v Západných Tatrách.",
"tvrdošín": "Tvrdošín je mestečko známe gotickým dreveným kostolíkom (UNESCO).",
"trstená": "Trstená je pohraničné mestečko s hraničným priechodom do Poľska.",
"nižná": "Nižná je väčšia obec v Oravskej kotline s priemyselným zázemím.",
"podbiel": "Podbiel má zachovanú tradičnú oravskú architektúru a je pamiatkovo chránený.",
"oravská priehrada": "Oravská priehrada je najväčšia vodná nádrž na Slovensku.",
"námestovo": "Námestovo je mesto na severe Slovenska pri Oravskej priehrade.",
"lokca": "Lokca je obec na severe Oravy s rázovitým charakterom.",
"mutné": "Mutné je malá horská obec v regióne Horná Orava.",
"oravská polhora": "Najsevernejšia obec Slovenska, známa prírodou a tradíciami.",
"rabča": "Rabča je väčšia obec pri Námestove, známa folklórom a zvonicou.",
"čimhová": "Čimhová je jedna z najstarších obcí na Orave, historicky významná.",
"hrabovo": "Hrabovo je lokalita pri Ružomberku známa lyžiarskym strediskom.",
"ružomberok": "Ružomberok je mesto na Liptove, známe aj textilnou a papierenskou výrobou.",
"likavka": "Likavka je obec pri Ružomberku s ruinou Likavského hradu.",
"liptovská osada": "Liptovská Osada je obec na ceste do Donovál v krásnom prostredí.",
"liptovská lúžna": "Obec v horách, známa ako jedna z najdlhších obcí Slovenska.",
"liptovský mikuláš": "Liptovský Mikuláš je centrum Liptova s bohatým kultúrnym životom.",
"demänovská dolina": "Demänovská dolina je oblasť s jaskyňami a lyžiarskym strediskom Jasná.",
"jasná": "Jasná je najväčšie lyžiarske stredisko na Slovensku v Nízkych Tatrách.",
"liptovský ján": "Liptovský Ján je obec známa termálnymi prameňmi a turistikou.",
"jalovec": "Jalovec je horská obec s výhľadom na Západné Tatry.",
"pribylina": "Pribylina je dedina pod Západnými Tatrami, známa skanzenom.",
"važec": "Važec je známa podtatranská obec s folklórnou tradíciou.",
"východná": "Východná je známa folklórnym festivalom a výhľadom na Tatry.",
"hybe": "Hybe je obec s literárnou históriou a tradíciami.",
"spišská teplica": "Spišská Teplica je podtatranská obec v blízkosti Popradu.",
"poprad": "Poprad je vstupná brána do Vysokých Tatier s letiskom a aquaparkom.",
"spišská sobota": "Historická časť Popradu s krásnymi meštianskymi domami.",
"veľká lomnica": "Veľká Lomnica je rekreačná obec pod Tatrami s golfovým areálom.",
"tatranská lomnica": "Tatranská Lomnica je známe tatranské stredisko s lanovkou na Lomnický štít.",
"starý smokovec": "Starý Smokovec je historické centrum Vysokých Tatier s električkou.",
"nový smokovec": "Nový Smokovec je kúpeľná časť Tatier s turistickým vybavením.",
"štrbské pleso": "Štrbské Pleso je známe jazero a športové stredisko vo Vysokých Tatrách.",
"štrba": "Štrba je obec pri Vysokých Tatrách, známa prestupnou železničnou stanicou.",
"lučivná": "Lučivná je tichá obec pod Tatrami so zámkom a rehabilitačným ústavom.",
"svit": "Svit je priemyselné mesto založené ako továreň na umelé vlákna.",
"batizovce": "Batizovce sú obec pod Tatrami s výhľadom na Gerlachovský štít.",
    };

  function getAIResponse(text) {
    const lower = text.toLowerCase().trim();
    if (lower.startsWith("vyhľadaj:")) {
      const query = lower.replace("vyhľadaj:", "").trim();
      window.open("https://www.google.com/search?q=" + encodeURIComponent(query), "_blank");
      return `🔍 Vyhľadávam: ${query}`;
    }
    return odpovede[lower] || "Prepáč, túto otázku ešte nepoznám.";
  }

  function addMessage(sender, text) {
    const msg = document.createElement("div");
    msg.className = "message";
    msg.innerHTML = `<strong>${sender}:</strong> ${text}`;
    chat.appendChild(msg);
    chat.scrollTop = chat.scrollHeight;
  }

  form.addEventListener("submit", function (e) {
    e.preventDefault();
    const userText = input.value.trim();
    if (!userText) return;

    addMessage("Ty", userText);
    const response = getAIResponse(userText);
    addMessage("ErikAI", response);
    input.value = "";
  });
});
